parameters:
  - name: serviceConnection
    type: string
  - name: environment
    type: string
    # Note: Approvals should be configured on the environment in Azure DevOps
    # Go to Pipelines > Environments > [environment name] > Approvals and checks
  - name: workingDirectory
    type: string
  - name: resourceType
    type: string
    # Short name for stage identifiers (e.g., "MG", "MG-Groups")
  - name: resourceDisplayName
    type: string
    # Full display name (e.g., "Management Groups", "MG Hierarchy")
  - name: runPlanInApply
    type: boolean
    default: false
    # Whether to run terraform plan before apply in the Apply stage
  - name: varFile
    type: string
    default: ''
    # Path to terraform variables file (e.g., 'mg.tfvars.json')
  - name: terraformVariables
    type: object
    default: []
    # Array of objects with 'name' and 'value' properties for Terraform variables

stages:
  # Plan Stage
  - stage: Plan_${{ parameters.resourceType }}_${{ parameters.environment }}
    displayName: 'Plan: ${{ parameters.resourceDisplayName }} (${{ parameters.environment }})'
    jobs:
      - job: TfPlan
        displayName: 'Plan: ${{ parameters.resourceDisplayName }} ${{ parameters.environment }}'
        steps:
          - task: AzureCLI@2
            displayName: "Plan: Terraform ${{ parameters.resourceDisplayName }}"
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                cd ${{ parameters.workingDirectory }}
                
                # Get Azure context and set ARM variables for Azure provider authentication
                SUBSCRIPTION_ID=$(az account show --query id -o tsv)
                TENANT_ID=$(az account show --query tenantId -o tsv)
                CLIENT_ID=$(az account show --query user.name -o tsv)
                
                # Set ARM environment variables for Terraform Azure provider
                export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
                export ARM_TENANT_ID=$TENANT_ID
                export ARM_CLIENT_ID=$CLIENT_ID
                export ARM_USE_OIDC=true
                
                # Unset Azure CLI config to force Terraform to use ARM variables instead of Azure CLI
                unset AZURE_CONFIG_DIR
                
                echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
                echo "ARM_TENANT_ID: $ARM_TENANT_ID"
                echo "ARM_CLIENT_ID: $ARM_CLIENT_ID"
                echo "ARM_USE_OIDC: $ARM_USE_OIDC"
                
                terraform init -upgrade
                
                # Unlock state if locked (replace with actual lock ID from error if different)
                # terraform force-unlock -force <LOCK_ID> || echo "Lock already released or unlock failed, continuing..."
                
                # Build terraform plan command with var file and variables
                PLAN_CMD="terraform plan"
                ${{ if ne(parameters.varFile, '') }}:
                PLAN_CMD="$PLAN_CMD -var-file=\"${{ parameters.varFile }}\""
                ${{ endif }}:
                ${{ each var in parameters.terraformVariables }}:
                PLAN_CMD="$PLAN_CMD -var=\"${{ var.name }}=${{ var.value }}\""
                ${{ end }}:
                
                $PLAN_CMD

  # Apply Stage
  - stage: Apply_${{ parameters.resourceType }}_${{ parameters.environment }}
    displayName: 'Apply: ${{ parameters.resourceDisplayName }} (${{ parameters.environment }})'
    dependsOn: Plan_${{ parameters.resourceType }}_${{ parameters.environment }}
    jobs:
      - deployment: TfApply
        displayName: 'Apply: ${{ parameters.resourceDisplayName }} ${{ parameters.environment }}'
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  displayName: "Apply: Terraform ${{ parameters.resourceDisplayName }}"
                  inputs:
                    azureSubscription: ${{ parameters.serviceConnection }}
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      cd ${{ parameters.workingDirectory }}
                       
                      # Get Azure context and set ARM variables for Azure provider authentication
                      SUBSCRIPTION_ID=$(az account show --query id -o tsv)
                      TENANT_ID=$(az account show --query tenantId -o tsv)
                      CLIENT_ID=$(az account show --query user.name -o tsv)
                      
                      # Set ARM environment variables for Terraform Azure provider
                      export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
                      export ARM_TENANT_ID=$TENANT_ID
                      export ARM_CLIENT_ID=$CLIENT_ID
                      export ARM_USE_OIDC=true
                      
                      # Unset Azure CLI config to force Terraform to use ARM variables instead of Azure CLI
                      unset AZURE_CONFIG_DIR
                      
                      echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
                      echo "ARM_TENANT_ID: $ARM_TENANT_ID"
                      echo "ARM_CLIENT_ID: $ARM_CLIENT_ID"
                      echo "ARM_USE_OIDC: $ARM_USE_OIDC"
                      
                      terraform init -upgrade
                      
                      # Unlock state if locked (replace with actual lock ID from error if different)
                      # terraform force-unlock -force <LOCK_ID> || echo "Lock already released or unlock failed, continuing..."
                      
                      # Build terraform commands with var file and variables
                      APPLY_CMD=""
                      ${{ if ne(parameters.varFile, '') }}:
                      APPLY_CMD="$APPLY_CMD -var-file=\"${{ parameters.varFile }}\""
                      ${{ endif }}:
                      ${{ each var in parameters.terraformVariables }}:
                      APPLY_CMD="$APPLY_CMD -var=\"${{ var.name }}=${{ var.value }}\""
                      ${{ end }}:
                      
                      if [ "${{ parameters.runPlanInApply }}" = "true" ]; then
                        terraform plan $APPLY_CMD
                      fi
                      
                      terraform apply -auto-approve $APPLY_CMD
