parameters:
  - name: serviceConnection
    type: string
  - name: subscriptionId
    type: string
  - name: environment
    type: string
  - name: workingDirectory
    type: string
  - name: resourceType
    type: string
  - name: resourceDisplayName
    type: string
  - name: runPlanInApply
    type: boolean
    default: false
  - name: varFile
    type: string
    default: ''
  - name: terraformVariables
    type: object
    default: []
  - name: backendResourceGroupName
    type: string
  - name: backendStorageAccountName
    type: string
  - name: backendContainerName
    type: string
  - name: backendKey
    type: string

stages:
  # Plan Stage
  - stage: Plan_${{ parameters.resourceType }}_${{ parameters.environment }}
    displayName: 'Plan: ${{ parameters.resourceDisplayName }} (${{ parameters.environment }})'
    jobs:
      - job: TfPlan
        displayName: 'Plan: ${{ parameters.resourceDisplayName }} ${{ parameters.environment }}'
        steps:
          - task: AzureCLI@2
            displayName: "Plan: Terraform ${{ parameters.resourceDisplayName }}"
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Set Azure subscription context
                az account set --subscription "${{ parameters.subscriptionId }}"
                
                cd ${{ parameters.workingDirectory }}

                # Get Azure context and set ARM variables for Azure provider authentication
                SUBSCRIPTION_ID=$(az account show --query id -o tsv)
                TENANT_ID=$(az account show --query tenantId -o tsv)
                CLIENT_ID=$(az account show --query user.name -o tsv)

                # Set ARM environment variables for Terraform Azure provider
                export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
                export ARM_TENANT_ID=$TENANT_ID
                export ARM_CLIENT_ID=$CLIENT_ID
                export ARM_USE_OIDC=true

                # Unset Azure CLI config to force Terraform to use ARM variables instead of Azure CLI
                unset AZURE_CONFIG_DIR

                echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
                echo "ARM_TENANT_ID: $ARM_TENANT_ID"
                echo "ARM_CLIENT_ID: $CLIENT_ID"
                echo "ARM_USE_OIDC: $ARM_USE_OIDC"

                terraform init -upgrade \
                  -backend-config="resource_group_name=${{ parameters.backendResourceGroupName }}" \
                  -backend-config="storage_account_name=${{ parameters.backendStorageAccountName }}" \
                  -backend-config="container_name=${{ parameters.backendContainerName }}" \
                  -backend-config="key=${{ parameters.backendKey }}"

                # Unlock state if locked (replace with actual lock ID from error if different)
                # terraform force-unlock -force 61227d1a-381b-6676-dfa7-fa3b93ce9895 || echo "Lock already released or unlock failed, continuing..."
                
                # Run plan and pass environment as a Terraform variable
                terraform plan -var "environment=${{ parameters.environment }}"

                # terraform import -var "environment=test" 'module.management_groups.module.first_level_mgs["platform"].azurerm_management_group.mg' /providers/Microsoft.Management/managementGroups/test-platform


  # Apply Stage
  - stage: Apply_${{ parameters.resourceType }}_${{ parameters.environment }}
    displayName: 'Apply: ${{ parameters.resourceDisplayName }} (${{ parameters.environment }})'
    dependsOn: Plan_${{ parameters.resourceType }}_${{ parameters.environment }}
    condition: succeeded()
    jobs:
      - deployment: TfApply
        displayName: 'Apply: ${{ parameters.resourceDisplayName }} ${{ parameters.environment }}'
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  displayName: "Apply: Terraform ${{ parameters.resourceDisplayName }}"
                  inputs:
                    azureSubscription: ${{ parameters.serviceConnection }}
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      # Set Azure subscription context
                      az account set --subscription "${{ parameters.subscriptionId }}"
                      
                      cd ${{ parameters.workingDirectory }}

                      # Get Azure context and set ARM variables for Azure provider authentication
                      SUBSCRIPTION_ID=$(az account show --query id -o tsv)
                      TENANT_ID=$(az account show --query tenantId -o tsv)
                      CLIENT_ID=$(az account show --query user.name -o tsv)

                      # Set ARM environment variables for Terraform Azure provider
                      export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
                      export ARM_TENANT_ID=$TENANT_ID
                      export ARM_CLIENT_ID=$CLIENT_ID
                      export ARM_USE_OIDC=true

                      # Unset Azure CLI config to force Terraform to use ARM variables instead of Azure CLI
                      unset AZURE_CONFIG_DIR

                      echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
                      echo "ARM_TENANT_ID: $ARM_TENANT_ID"
                      echo "ARM_CLIENT_ID: $CLIENT_ID"
                      echo "ARM_USE_OIDC: $ARM_USE_OIDC"

                      terraform init -upgrade \
                        -backend-config="resource_group_name=${{ parameters.backendResourceGroupName }}" \
                        -backend-config="storage_account_name=${{ parameters.backendStorageAccountName }}" \
                        -backend-config="container_name=${{ parameters.backendContainerName }}" \
                        -backend-config="key=${{ parameters.backendKey }}"

                      # Optionally run plan before apply if runPlanInApply is true
                      if [ "${{ parameters.runPlanInApply }}" = "true" ]; then
                        terraform plan -var "environment=${{ parameters.environment }}"
                      fi

                      # Run apply and pass environment as a Terraform variable
                      terraform apply -auto-approve -var "environment=${{ parameters.environment }}"
