trigger:
  branches:
    include:
      - main
  paths:
    include:
      - mg/**
      - modules/**
      - pipeline/**

pool: default

variables:
  serviceConnectionDev: 'id-mg-vending-eus-dev-001'

stages:
  # Dev Environment - Plan and Apply
  - template: templates/deploy-terraform.yaml
    parameters:
      serviceConnection: $(serviceConnectionDev)
      environment: 'Dev'
      workingDirectory: 'mg'
      resourceType: 'MG'
      resourceDisplayName: 'Management Groups'
      runPlanInApply: false
