trigger:
  branches:
    include:
      - main
  paths:
    include:
      - mg/**
      - modules/**
      - pipeline/**

pool: default

variables:
  serviceConnectionDev: 'id-mg-vending-eus-dev-001'
  # serviceConnectionTest: '<test-service-connection-name>'
  # serviceConnectionProd: '<prod-service-connection-name>'

stages:
  # Dev Environment - Plan and Apply
  - template: templates/deploy-terraform.yaml
    parameters:
      serviceConnection: $(serviceConnectionDev)
      environment: 'Dev'
      workingDirectory: 'mg'
      resourceType: 'MG'
      resourceDisplayName: 'Management Groups'
      runPlanInApply: false

  # # Test Environment - Plan, Approval, Apply
  # - template: templates/deploy-terraform.yaml
  #   parameters:
  #     serviceConnection: $(serviceConnectionTest)
  #     environment: 'Test'
  #     workingDirectory: 'mg'
  #     resourceType: 'MG'
  #     resourceDisplayName: 'Management Groups'
  #     runPlanInApply: false

  # # Prod Environment - Plan, Approval, Apply
  # - template: templates/deploy-terraform.yaml
  #   parameters:
  #     serviceConnection: $(serviceConnectionProd)
  #     environment: 'Prod'
  #     workingDirectory: 'mg'
  #     resourceType: 'MG'
  #     resourceDisplayName: 'Management Groups'
  #     runPlanInApply: false
